### ISSUE TITLE
Hue Lights weird status updates in zway 2.3.6 on WD

### ISSUE THREAD

**Issue by LeoGr13** [timauton/Hue#6]
Hi,
some of my hue lights are constantly refreshing their status. Should not be a problem, but the status changes from 99% to 0% and so on. Meanwhile the lights are continous off. Sometimes there are no issues and sometimes it happens like described.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/34006075/33241832-d41afffc-d2cb-11e7-8f5b-178d6f5736b5.png)

**Comment by konterr** [comment]
Hi,
I do have the same issue on an Razberry. Everything works, but this makes the event log useless since a few lamps spam so entries that everything interesting in there gets pushed out of the 2500 entries.
For me it started with the bulb that got id 10 from the hue bridge.

**Comment by timauton** [comment]
Apologies for not responding sooner, I've been missing my Github emails.

I've not been able to reproduce this issue myself, but I have merged some changes from klaasjoerg which control the rate of requests to the Hue hub to stop it getting confused. Can you try the latest release and see if that resolves the issue?

**Comment by LeoGr13** [comment]
Hi,
do you know how to update the version on a WD mycloud based system? In the Zway Appstore im only able to download 0,98 beta.

Thank you for the support, im looking forward to test the new release!

**Comment by timauton** [comment]
This is a fork of the original module by the user Minux, whose version is on the App store. To install this version you'd need to connect via ssh and follow the instructions [on the forum here](https://forum.z-wave.me/viewtopic.php?f=3419&t=24012&p=66872#p66945).

Unfortunately Minux doesn't seem to have a public github to push updates to. I'll drop them a forum message to ask them to update.

**Comment by LeoGr13** [comment]
Thanks for the info and your work. Installing Git on the WD PR System was a bit tricky but im using now your latest release. I will report feedback within the next few days.

**Comment by LeoGr13** [comment]
I think that the problem is not solved but im now only getting such a false on/off report once a day (from 4-5 lights) and not every minute, like in the previous version.
For me its perfectly fine now, as im able to use the event log again!

Thanks for your work!
